# Generated by Django 4.1 on 2023-09-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test01", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="age",
            field=models.IntegerField(),
        ),
    ]
