# Generated by Django 4.1 on 2023-12-16 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("test01", "0002_alter_userinfo_age"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaType",
            fields=[
                (
                    "media_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.IntegerField(primary_key=True, serialize=False)),
                ("question_title", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "question_category_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("question_category", models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionType",
            fields=[
                (
                    "question_type_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("question_type", models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("survey_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="QuestionHasSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="test01.question",
                    ),
                ),
                (
                    "survey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="test01.survey"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionHasQuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test01.question",
                    ),
                ),
                (
                    "question_category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test01.questioncategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test01.questiontype",
            ),
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("option_id", models.IntegerField(primary_key=True, serialize=False)),
                ("option_description", models.CharField(max_length=45, null=True)),
                ("option_correct", models.BooleanField()),
                (
                    "media_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test01.mediatype",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="test01.question",
                    ),
                ),
            ],
        ),
    ]
